### PR TITLE
merge twitter twemproxy master changes

### PR DESCRIPTION
**Pull request by andyqzb**

### CODE REVIEW

**Comment by aibibang** [comment]
hi,
my nutcracker.yml
sigma:
  listen: 127.0.0.1:22125
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  redis: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
    - 127.0.0.1:6383:1
    - 127.0.0.1:6380:1
  sentinels:
    - 127.0.0.1:63830:1
    - 127.0.0.1:63800:1

6383 master 6381slave

6380 master 6382slave

kill 6380

why no effect?

127.0.0.1:22125> set zz zzz
(error) ERR Connection refused

**Comment by mishan** [comment]
Because you forgot to name your Redis nodes. You can name them something like ... db01 db02 (it has to *match* what the Sentinel identifies them as)

  servers:
    - 127.0.0.1:6383:1 db01
    - 127.0.0.1:6380:1 db02
  sentinels:
    - 127.0.0.1:63830:1
    - 127.0.0.1:63800:1

Then it will work.

**Comment by aibibang** [comment]
@mishan  not work.
<pre><code>
[root@SXLAB29 twemproxy-ha_with_sentinel_rebase]# 20016:X 04 Feb 14:26:02.360 # +sdown master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.360 # +odown master mymaster1 127.0.0.1 6380 #quorum 1/1
20016:X 04 Feb 14:26:02.360 # +new-epoch 13
20016:X 04 Feb 14:26:02.360 # +try-failover master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.434 # +vote-for-leader 6b65bc60f390478a653d777622afaec8ca1408a7 13
20016:X 04 Feb 14:26:02.434 # +elected-leader master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.434 # +failover-state-select-slave master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.525 # +selected-slave slave 127.0.0.1:6382 127.0.0.1 6382 @ mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.525 * +failover-state-send-slaveof-noone slave 127.0.0.1:6382 127.0.0.1 6382 @ mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:02.580 * +failover-state-wait-promotion slave 127.0.0.1:6382 127.0.0.1 6382 @ mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:03.516 # +promoted-slave slave 127.0.0.1:6382 127.0.0.1 6382 @ mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:03.516 # +failover-state-reconf-slaves master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:03.516 # +failover-end master mymaster1 127.0.0.1 6380
20016:X 04 Feb 14:26:03.516 # +switch-master mymaster1 127.0.0.1 6380 127.0.0.1 6382
20016:X 04 Feb 14:26:03.517 * +slave slave 127.0.0.1:6380 127.0.0.1 6380 @ mymaster1 127.0.0.1 6382
20016:X 04 Feb 14:26:08.539 # +sdown slave 127.0.0.1:6380 127.0.0.1 6380 @ mymaster1 127.0.0.1 6382

[root@SXLAB29 twemproxy-ha_with_sentinel_rebase]# redis-cli -p 22125
127.0.0.1:22125> get b
(error) ERR Connection refused
</code></pre>
redis version 2.8.4 
have no idea.

**Comment by aibibang** [comment]
@mishan thanks ,it work

**Pull request merged**
